FROM alpine:latest

RUN apk update && \
  apk add --no-cache \
  build-base \
  gcc \
  libc-dev \
  python3 \
  curl

RUN curl https://raw.githubusercontent.com/cd-c89/crypto/main/enigma/tester.py -o tester.py

COPY ./enigma.c .

RUN gcc -o enigma.out enigma.c
